### ISSUE TITLE
增加新版本提示公告模版接口

### ISSUE THREAD

**Issue by Masterain98** [DGP-Studio/Snap.Hutao.Server#10]
设计一个用于自动化流程触发的新版本提示公告的发布接口
- 传入参数为版本号，如 `?template=update&v=1.7.4`
- 模版内容须要提醒用户在 MS Store/GitHub 获取更新
- 查看详情按钮可以定向至文档页面，如：`https://hut.ao/statements/update-log.html#_1-7-4`

**Comment by Masterain98** [comment]
查看详情跳转到商店页面也是不错的选择，可以直接 `ms-windows-store://pdp/?ProductId=9PH4NXJ2JN52`，亦或者可以增加按钮

**Comment by Lightczx** [comment]
模板文本怎么写
