### ISSUE TITLE
[Bug]:上传深渊502错误

### ISSUE THREAD

**Issue by halointernet** [DGP-Studio/Snap.Hutao.Server#59]
### Windows 版本

22621.521

### Snap Hutao 版本

1.12.5.0

### 设备 ID

142B7FE807BE1FC30C5B8C874F397C57

### 问题分类

深境螺旋/胡桃数据库

### 发生了什么？

上传深渊502错误![Image](https://github.com/user-attachments/assets/4406f3a3-517c-4dc9-ba2d-9440b94baf44)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
![Image](https://github.com/user-attachments/assets/cf272af4-2612-4662-8881-6143d89ee78a)
@Masterain98
